##
## @doc
##   Cloud Formation template to spawns AWS resources, which are required for appliance operation.
AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Spawn AWS resource for Datomic solution.

Parameters:

  Solution:
    Type: String
    Description: |
      Name of the solution

  Env:
    Type: String
    Default: dev
    Description: |
      Deployment Environment for the solution

##
##
Resources:

  DynamoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Join:
          - "-"
          -
            - !Ref Env
            - "datomic"
            - !Ref Solution

      AttributeDefinitions:
        -
          AttributeName: id
          AttributeType: S

      KeySchema:
        -
          AttributeName: id
          KeyType: HASH

      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5


  ClusterRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 
        Fn::Join:
          - "-"
          -
            - !Ref Env
            - "datomic"
            - !Ref Solution
            - "cluster"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: AmazonDynamoDBFullAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource: 
                  Fn::Join:
                    - ""
                    -
                      - "arn:aws:dynamodb:"
                      - !Ref "AWS::Region" 
                      - ":"
                      - !Ref "AWS::AccountId"
                      - ":table/"
                      - !Ref "DynamoDB"

        - PolicyName: DatomicArtifactsReadOnly
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  Fn::Join:
                    - ""
                    -
                      - "arn:aws:s3:::"
                      - !ImportValue "s3-datomic-artifacts"
                      - "/*"

        - PolicyName: AllowKMSDecryption
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                  - kms:Decrypt
                Resource: 
                  - !ImportValue "kms-datomic-license-encryption-key"

        - PolicyName: AllowCloudWatch
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                  - cloudwatch:PutMetricDataBatch
                Resource: "*"
                Condition:
                  Bool:
                    aws:SecureTransport: true

  PeerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 
        Fn::Join:
          - "-"
          -
            - !Ref Env
            - "datomic"
            - !Ref Solution
            - "peer"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:BatchGetItem
                  - dynamodb:Scan
                  - dynamodb:Query
                Resource: 
                  Fn::Join:
                    - ""
                    -
                      - "arn:aws:dynamodb:"
                      - !Ref "AWS::Region" 
                      - ":"
                      - !Ref "AWS::AccountId"
                      - ":table/"
                      - !Ref "DynamoDB"
